app = "cinema-mvc"
primary_region = "ord"  # Change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  DOTNET_RUNNING_IN_CONTAINER = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
